# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "Stash",
    "StashesBinaryPath",
    "StashesTextContent",
)

import datetime
import pydantic
import typing

if typing.TYPE_CHECKING:
    import collections.abc


class Stash(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    is_binary: bool
    slug: str
    added: datetime.datetime


class StashesBinaryPath(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    stash_id: int
    file_path: str


class StashesTextContent(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    stash_id: int
    content: str
