# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "Stash",
    "StashLockout",
    "StashPasswordAttempt",
    "StashView",
    "StashesBinaryPath",
    "StashesExpiry",
    "StashesOneTimeView",
    "StashesPasswordHash",
    "StashesRevocation",
    "StashesTextContent",
)

import datetime
import pydantic
import typing

if typing.TYPE_CHECKING:
    import collections.abc


class Stash(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    is_binary: bool
    slug: str
    added: datetime.datetime
    added_by_ip: str


class StashLockout(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    stash_id: int
    ip_address: str
    added: datetime.datetime
    expires: datetime.datetime


class StashPasswordAttempt(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    stash_id: int
    ip_address: str
    successful: bool
    attempted_at: datetime.datetime


class StashView(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    stash_id: int
    ip_address: str
    viewed_at: datetime.datetime


class StashesBinaryPath(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    stash_id: int
    file_path: str


class StashesExpiry(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    stash_id: int
    expires_at: datetime.datetime


class StashesOneTimeView(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    stash_id: int


class StashesPasswordHash(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    stash_id: int
    password_hash: str


class StashesRevocation(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    stash_id: int
    revoked_at: datetime.datetime
    revoked_by_ip: str


class StashesTextContent(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    stash_id: int
    content: str
