# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: query.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "GetActiveStashLockoutRow",
    "GetStashBySlugRow",
    "GetStashRow",
    "QueryResults",
    "check_slug_exists",
    "create_stash",
    "create_stash_binary_path",
    "create_stash_lockout",
    "create_stash_password_attempt",
    "create_stash_text_content",
    "create_stash_view",
    "get_active_stash_lockout",
    "get_stash",
    "get_stash_binary_path",
    "get_stash_by_slug",
    "get_stash_text_content",
    "get_stash_unique_views",
    "get_stash_unique_views_by_slug",
    "get_stash_views",
    "get_stash_views_by_slug",
    "list_stashes",
)

import datetime
import pydantic
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import psycopg
    import psycopg.rows

    type QueryResultsArgsType = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = psycopg.AsyncConnection[psycopg.rows.TupleRow]

from db import models


class GetStashRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    is_binary: bool
    slug: str
    added: datetime.datetime
    added_by_ip: str
    expires_at: datetime.datetime | None
    one_time_view: bool
    password_hash: str | None
    revoked_at: datetime.datetime | None
    revoked_by_ip: str | None


class GetStashBySlugRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    is_binary: bool
    added: datetime.datetime
    added_by_ip: str
    expires_at: datetime.datetime | None
    one_time_view: bool
    password_hash: str | None
    revoked_at: datetime.datetime | None
    revoked_by_ip: str | None


class GetActiveStashLockoutRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    added: datetime.datetime
    expires: datetime.datetime


GET_STASH: typing.Final[typing.LiteralString] = """-- name: GetStash :one
SELECT
    is_binary,
    slug,
    added,
    added_by_ip,
    expires_at,
    one_time_view,
    password_hash,
    revoked_at,
    revoked_by_ip
FROM stashes
WHERE id = %(p1)s
"""

GET_STASH_BY_SLUG: typing.Final[typing.LiteralString] = """-- name: GetStashBySlug :one
SELECT
    id,
    is_binary,
    added,
    added_by_ip,
    expires_at,
    one_time_view,
    password_hash,
    revoked_at,
    revoked_by_ip
FROM stashes
WHERE slug = %(p1)s
"""

LIST_STASHES: typing.Final[typing.LiteralString] = """-- name: ListStashes :many
SELECT id, is_binary, slug, added, added_by_ip, expires_at, one_time_view, password_hash, revoked_at, revoked_by_ip 
FROM stashes
ORDER BY added DESC, id DESC
LIMIT %(p1)s OFFSET %(p2)s
"""

GET_STASH_TEXT_CONTENT: typing.Final[typing.LiteralString] = """-- name: GetStashTextContent :one
SELECT content
FROM stashes_text_content
WHERE stash_id = %(p1)s
"""

GET_STASH_BINARY_PATH: typing.Final[typing.LiteralString] = """-- name: GetStashBinaryPath :one
SELECT file_path
FROM stashes_binary_paths
WHERE stash_id = %(p1)s
"""

CREATE_STASH: typing.Final[typing.LiteralString] = """-- name: CreateStash :one
INSERT INTO stashes (is_binary, slug, added_by_ip)
VALUES (%(p1)s, %(p2)s, %(p3)s)
RETURNING id, is_binary, slug, added, added_by_ip, expires_at, one_time_view, password_hash, revoked_at, revoked_by_ip
"""

CREATE_STASH_TEXT_CONTENT: typing.Final[typing.LiteralString] = """-- name: CreateStashTextContent :exec
INSERT INTO stashes_text_content (stash_id, content)
VALUES (%(p1)s, %(p2)s)
"""

CREATE_STASH_BINARY_PATH: typing.Final[typing.LiteralString] = """-- name: CreateStashBinaryPath :exec
INSERT INTO stashes_binary_paths (stash_id, file_path)
VALUES (%(p1)s, %(p2)s)
"""

CHECK_SLUG_EXISTS: typing.Final[typing.LiteralString] = """-- name: CheckSlugExists :one
SELECT EXISTS (
    SELECT 1
    FROM stashes
    WHERE slug = %(p1)s
)
"""

CREATE_STASH_VIEW: typing.Final[typing.LiteralString] = """-- name: CreateStashView :exec
INSERT INTO stash_views (stash_id, ip_address)
VALUES (%(p1)s, %(p2)s)
"""

CREATE_STASH_PASSWORD_ATTEMPT: typing.Final[typing.LiteralString] = """-- name: CreateStashPasswordAttempt :exec
INSERT INTO stash_password_attempts (
    stash_id,
    ip_address,
    successful
)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

CREATE_STASH_LOCKOUT: typing.Final[typing.LiteralString] = """-- name: CreateStashLockout :exec
INSERT INTO stash_lockouts (
    stash_id,
    ip_address,
    expires
)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

GET_ACTIVE_STASH_LOCKOUT: typing.Final[typing.LiteralString] = """-- name: GetActiveStashLockout :one
SELECT
    id,
    added,
    expires
FROM stash_lockouts
WHERE stash_id = %(p1)s
  AND ip_address = %(p2)s
  AND expires > CURRENT_TIMESTAMP
ORDER BY expires DESC
LIMIT 1
"""

GET_STASH_VIEWS: typing.Final[typing.LiteralString] = """-- name: GetStashViews :one
SELECT COUNT(*)
FROM stash_views
WHERE stash_id = %(p1)s
"""

GET_STASH_UNIQUE_VIEWS: typing.Final[typing.LiteralString] = """-- name: GetStashUniqueViews :one
SELECT COUNT(DISTINCT ip_address)
FROM stash_views
WHERE stash_id = %(p1)s
"""

GET_STASH_VIEWS_BY_SLUG: typing.Final[typing.LiteralString] = """-- name: GetStashViewsBySlug :one
SELECT COUNT(*)
FROM stash_views
JOIN stashes ON stashes.id = stash_views.stash_id
WHERE stashes.slug = %(p1)s
"""

GET_STASH_UNIQUE_VIEWS_BY_SLUG: typing.Final[typing.LiteralString] = """-- name: GetStashUniqueViewsBySlug :one
SELECT COUNT(DISTINCT stash_views.ip_address)
FROM stash_views
JOIN stashes ON stashes.id = stash_views.stash_id
WHERE stashes.slug = %(p1)s
"""


class QueryResults[T]:
    __slots__ = ("_conn", "_cursor", "_decode_hook", "_iterator", "_params", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: typing.LiteralString,
        decode_hook: collections.abc.Callable[[psycopg.rows.TupleRow], T],
        params: dict[str, QueryResultsArgsType] | None = None,
    ) -> None:
        self._conn = conn
        self._sql: typing.LiteralString = sql
        self._decode_hook = decode_hook
        self._params = params
        self._cursor: psycopg.AsyncCursor[psycopg.rows.TupleRow] | None = None
        self._iterator: collections.abc.AsyncIterator[psycopg.rows.TupleRow] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await (await self._conn.execute(self._sql, self._params)).fetchall()
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = await self._conn.execute(self._sql, self._params)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def get_stash(conn: ConnectionLike, *, id_: int) -> GetStashRow | None:
    row = await (await conn.execute(GET_STASH, {"p1": id_})).fetchone()
    if row is None:
        return None
    return GetStashRow(is_binary=row[0], slug=row[1], added=row[2], added_by_ip=str(row[3]), expires_at=row[4], one_time_view=row[5], password_hash=row[6], revoked_at=row[7], revoked_by_ip=str(row[8]) if row[8] is not None else None)


async def get_stash_by_slug(conn: ConnectionLike, *, slug: str) -> GetStashBySlugRow | None:
    row = await (await conn.execute(GET_STASH_BY_SLUG, {"p1": slug})).fetchone()
    if row is None:
        return None
    return GetStashBySlugRow(id_=row[0], is_binary=row[1], added=row[2], added_by_ip=str(row[3]), expires_at=row[4], one_time_view=row[5], password_hash=row[6], revoked_at=row[7], revoked_by_ip=str(row[8]) if row[8] is not None else None)


def list_stashes(conn: ConnectionLike, *, limit: int, offset: int) -> QueryResults[models.Stash]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> models.Stash:
        return models.Stash(id_=row[0], is_binary=row[1], slug=row[2], added=row[3], added_by_ip=str(row[4]), expires_at=row[5], one_time_view=row[6], password_hash=row[7], revoked_at=row[8], revoked_by_ip=str(row[9]) if row[9] is not None else None)

    return QueryResults(conn, LIST_STASHES, _decode_hook, {"p1": limit, "p2": offset})


async def get_stash_text_content(conn: ConnectionLike, *, stash_id: int) -> str | None:
    row = await (await conn.execute(GET_STASH_TEXT_CONTENT, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_stash_binary_path(conn: ConnectionLike, *, stash_id: int) -> str | None:
    row = await (await conn.execute(GET_STASH_BINARY_PATH, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_stash(conn: ConnectionLike, *, is_binary: bool, slug: str, added_by_ip: str) -> models.Stash | None:
    row = await (await conn.execute(CREATE_STASH, {"p1": is_binary, "p2": slug, "p3": added_by_ip})).fetchone()
    if row is None:
        return None
    return models.Stash(id_=row[0], is_binary=row[1], slug=row[2], added=row[3], added_by_ip=str(row[4]), expires_at=row[5], one_time_view=row[6], password_hash=row[7], revoked_at=row[8], revoked_by_ip=str(row[9]) if row[9] is not None else None)


async def create_stash_text_content(conn: ConnectionLike, *, stash_id: int, content: str) -> None:
    await conn.execute(CREATE_STASH_TEXT_CONTENT, {"p1": stash_id, "p2": content})


async def create_stash_binary_path(conn: ConnectionLike, *, stash_id: int, file_path: str) -> None:
    await conn.execute(CREATE_STASH_BINARY_PATH, {"p1": stash_id, "p2": file_path})


async def check_slug_exists(conn: ConnectionLike, *, slug: str) -> bool | None:
    row = await (await conn.execute(CHECK_SLUG_EXISTS, {"p1": slug})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_stash_view(conn: ConnectionLike, *, stash_id: int, ip_address: str) -> None:
    await conn.execute(CREATE_STASH_VIEW, {"p1": stash_id, "p2": ip_address})


async def create_stash_password_attempt(conn: ConnectionLike, *, stash_id: int, ip_address: str, successful: bool) -> None:
    await conn.execute(CREATE_STASH_PASSWORD_ATTEMPT, {"p1": stash_id, "p2": ip_address, "p3": successful})


async def create_stash_lockout(conn: ConnectionLike, *, stash_id: int, ip_address: str, expires: datetime.datetime) -> None:
    await conn.execute(CREATE_STASH_LOCKOUT, {"p1": stash_id, "p2": ip_address, "p3": expires})


async def get_active_stash_lockout(conn: ConnectionLike, *, stash_id: int, ip_address: str) -> GetActiveStashLockoutRow | None:
    row = await (await conn.execute(GET_ACTIVE_STASH_LOCKOUT, {"p1": stash_id, "p2": ip_address})).fetchone()
    if row is None:
        return None
    return GetActiveStashLockoutRow(id_=row[0], added=row[1], expires=row[2])


async def get_stash_views(conn: ConnectionLike, *, stash_id: int) -> int | None:
    row = await (await conn.execute(GET_STASH_VIEWS, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_stash_unique_views(conn: ConnectionLike, *, stash_id: int) -> int | None:
    row = await (await conn.execute(GET_STASH_UNIQUE_VIEWS, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_stash_views_by_slug(conn: ConnectionLike, *, slug: str) -> int | None:
    row = await (await conn.execute(GET_STASH_VIEWS_BY_SLUG, {"p1": slug})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_stash_unique_views_by_slug(conn: ConnectionLike, *, slug: str) -> int | None:
    row = await (await conn.execute(GET_STASH_UNIQUE_VIEWS_BY_SLUG, {"p1": slug})).fetchone()
    if row is None:
        return None
    return row[0]
