[tools]
uv = "latest"
python = "3.14"
node = "24"
sqlc = "latest"

[tasks.default]
run = "uv run --project api ruff check --fix --select I api"
sources = ["api/**/*.py"]

[tasks.sqlc]
run = "sqlc generate --file api/db/sqlc.yaml"
sources = ["api/db/*.sql", "api/db/sqlc.yaml"]
