proper_nouns = [
    "cartman",
    "john",
    "homer",
    "marge",
    "bart",
    "josh",
    "ratboy",
    "uncle",
    "nephew",
    "ferris",
    "goldie",
    "jeff",
    "bob",
    "leo",
    "zoe",
    "amy",
    "jax",
    "roy",
    "ray",
    "lea",
    "bret",
    "carl",
    "chad",
    "dean",
    "ed",
    "eddy",
    "gina",
    "paul",
    "greg",
    "cass",
    "chloe",
    "corey",
    "duke",
    "dave",
    "brad",
    "god",
    "dad",
    "mother",
    "father",
    "doc",
    "sid",
    "rod",
    "ned",
]

common_nouns = [
    "pigeon",
    "dog",
    "boy",
    "hacker",
    "rat",
    "man",
    "chad",
    "hen",
    "bum",
    "nun",
    "hun",
    "ox",
    "worm",
    "jury",
    "boss",
    "horse",
    "cat",
    "judge",
    "cop",
    "cow",
    "pig",
    "bird",
    "mage",
    "wizard",
    "elf",
    "hobbit",
    "dwarf",
    "troll",
    "orc",
    "dad",
    "doctor",
    "uncle",
    "nephew",
    "loser",
    "simp",
]

verbs = [
    "kick",
    "eat",
    "hack",
    "assault",
    "hold",
    "marry",
    "kill",
    "bake",
    "bomb",
    "love",
    "catch",
    "hex",
    "vex",
    "wield",
    "scam",
    "stalk",
    "slap",
    "whack",
    "summon",
    "bite",
    "need",
    "want",
    "buy",
    "sell",
    "sniff",
    "lick",
    "hunt",
    "shoot",
    "mug",
    "smash",
    "haunt",
    "blame",
    "charm",
    "ban",
    "hug",
    "break",
    "abuse",
    "align",
    "allow",
    "attract",
    "avail",
    "avenge",
    "betray",
    "battle",
    "beg",
    "bench",
    "confuse",
    "bonk",
    "boop",
    "bug",
    "call",
    "cancel",
    "carry",
    "con",
    "see",
    "cut",
    "try",
    "get",
    "win",
    "pay",
    "use",
    "tap",
    "take",
    "tell",
    "feel",
    "show",
    "help",
    "meet",
    "drop",
    "vote",
    "hide",
    "seek",
    "cook",
    "wake",
    "wash",
    "burn",
    "join",
    "save",
    "hear",
    "mog",
    "banish",
]

adjectives = [
    "smooth",
    "cooked",
    "bent",
    "pale",
    "upset",
    "smart",
    "dumb",
    "stupid",
    "amazed",
    "honest",
    "drunk",
    "toxic",
    "feral",
    "shady",
    "greasy",
    "mean",
    "sad",
    "scary",
    "goofy",
    "angry",
    "cute",
    "fast",
    "mad",
    "sick",
    "ugly",
    "bald",
    "lame",
    "fake",
    "loco",
    "red",
    "green",
    "blue",
    "gold",
    "black",
    "white",
    "faded",
    "pink",
    "big",
    "small",
    "gay",
    "new",
    "old",
    "lone",
    "single",
    "double",
    "triple",
    "second",
    "third",
    "lazy",
    "fat",
    "skinny",
]

adverbs = [
    "soon",
    "now",
    "hard",
    "far",
    "home",
    "awry",
    "cold",
    "today",
    "early",
    "twice",
    "once",
    "thrice",
]

articles = [
    "a",
    "the",
]

conjunctions = [
    "for", 
    "and", 
    "but",
    "yet",
    "so",
]