// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AddBinaryStashApiV1StashesFilePostData, AddBinaryStashApiV1StashesFilePostErrors, AddBinaryStashApiV1StashesFilePostResponses, AddTextStashApiV1StashesTextPostData, AddTextStashApiV1StashesTextPostErrors, AddTextStashApiV1StashesTextPostResponses, GetFileStashApiV1StashesFileSlugGetData, GetFileStashApiV1StashesFileSlugGetErrors, GetFileStashApiV1StashesFileSlugGetResponses, GetStashMetadataApiV1StashesMetadataSlugGetData, GetStashMetadataApiV1StashesMetadataSlugGetErrors, GetStashMetadataApiV1StashesMetadataSlugGetResponses, GetTextStashApiV1StashesTextSlugGetData, GetTextStashApiV1StashesTextSlugGetErrors, GetTextStashApiV1StashesTextSlugGetResponses, ListStashesApiV1StashesGetData, ListStashesApiV1StashesGetErrors, ListStashesApiV1StashesGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Stashes
 */
export const listStashesApiV1StashesGet = <ThrowOnError extends boolean = false>(options?: Options<ListStashesApiV1StashesGetData, ThrowOnError>): RequestResult<ListStashesApiV1StashesGetResponses, ListStashesApiV1StashesGetErrors, ThrowOnError> => (options?.client ?? client).get<ListStashesApiV1StashesGetResponses, ListStashesApiV1StashesGetErrors, ThrowOnError>({ url: '/api/v1/stashes/', ...options });

/**
 * Add Text Stash
 */
export const addTextStashApiV1StashesTextPost = <ThrowOnError extends boolean = false>(options: Options<AddTextStashApiV1StashesTextPostData, ThrowOnError>): RequestResult<AddTextStashApiV1StashesTextPostResponses, AddTextStashApiV1StashesTextPostErrors, ThrowOnError> => (options.client ?? client).post<AddTextStashApiV1StashesTextPostResponses, AddTextStashApiV1StashesTextPostErrors, ThrowOnError>({
    url: '/api/v1/stashes/text',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add Binary Stash
 */
export const addBinaryStashApiV1StashesFilePost = <ThrowOnError extends boolean = false>(options: Options<AddBinaryStashApiV1StashesFilePostData, ThrowOnError>): RequestResult<AddBinaryStashApiV1StashesFilePostResponses, AddBinaryStashApiV1StashesFilePostErrors, ThrowOnError> => (options.client ?? client).post<AddBinaryStashApiV1StashesFilePostResponses, AddBinaryStashApiV1StashesFilePostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/stashes/file',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get File Stash
 */
export const getFileStashApiV1StashesFileSlugGet = <ThrowOnError extends boolean = false>(options: Options<GetFileStashApiV1StashesFileSlugGetData, ThrowOnError>): RequestResult<GetFileStashApiV1StashesFileSlugGetResponses, GetFileStashApiV1StashesFileSlugGetErrors, ThrowOnError> => (options.client ?? client).get<GetFileStashApiV1StashesFileSlugGetResponses, GetFileStashApiV1StashesFileSlugGetErrors, ThrowOnError>({ url: '/api/v1/stashes/file/{slug}', ...options });

/**
 * Get Text Stash
 */
export const getTextStashApiV1StashesTextSlugGet = <ThrowOnError extends boolean = false>(options: Options<GetTextStashApiV1StashesTextSlugGetData, ThrowOnError>): RequestResult<GetTextStashApiV1StashesTextSlugGetResponses, GetTextStashApiV1StashesTextSlugGetErrors, ThrowOnError> => (options.client ?? client).get<GetTextStashApiV1StashesTextSlugGetResponses, GetTextStashApiV1StashesTextSlugGetErrors, ThrowOnError>({ url: '/api/v1/stashes/text/{slug}', ...options });

/**
 * Get Stash Metadata
 */
export const getStashMetadataApiV1StashesMetadataSlugGet = <ThrowOnError extends boolean = false>(options: Options<GetStashMetadataApiV1StashesMetadataSlugGetData, ThrowOnError>): RequestResult<GetStashMetadataApiV1StashesMetadataSlugGetResponses, GetStashMetadataApiV1StashesMetadataSlugGetErrors, ThrowOnError> => (options.client ?? client).get<GetStashMetadataApiV1StashesMetadataSlugGetResponses, GetStashMetadataApiV1StashesMetadataSlugGetErrors, ThrowOnError>({ url: '/api/v1/stashes/metadata/{slug}', ...options });
