// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AddBinaryStashApiV1StashesFilePostData, AddBinaryStashApiV1StashesFilePostErrors, AddBinaryStashApiV1StashesFilePostResponses, AddTextStashApiV1StashesTextPostData, AddTextStashApiV1StashesTextPostErrors, AddTextStashApiV1StashesTextPostResponses, GetConfigApiV1ConfigMaxUploadBytesGetData, GetConfigApiV1ConfigMaxUploadBytesGetErrors, GetConfigApiV1ConfigMaxUploadBytesGetResponses, GetFileStashApiV1StashesFileSlugGetData, GetFileStashApiV1StashesFileSlugGetErrors, GetFileStashApiV1StashesFileSlugGetResponses, GetMeApiV1AuthGoogleMeGetData, GetMeApiV1AuthGoogleMeGetErrors, GetMeApiV1AuthGoogleMeGetResponses, GetStashMetadataApiV1StashesMetadataSlugGetData, GetStashMetadataApiV1StashesMetadataSlugGetErrors, GetStashMetadataApiV1StashesMetadataSlugGetResponses, GetStashViewsApiV1StashesViewsSlugGetData, GetStashViewsApiV1StashesViewsSlugGetErrors, GetStashViewsApiV1StashesViewsSlugGetResponses, GetTextStashApiV1StashesTextSlugGetData, GetTextStashApiV1StashesTextSlugGetErrors, GetTextStashApiV1StashesTextSlugGetResponses, GoogleCallbackApiV1AuthGoogleCallbackGetData, GoogleCallbackApiV1AuthGoogleCallbackGetErrors, GoogleLoginApiV1AuthGoogleGetData, GoogleLoginApiV1AuthGoogleGetErrors, GoogleLoginApiV1AuthGoogleGetResponses, ListStashesApiV1StashesGetData, ListStashesApiV1StashesGetErrors, ListStashesApiV1StashesGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Stashes
 */
export const listStashesApiV1StashesGet = <ThrowOnError extends boolean = false>(options: Options<ListStashesApiV1StashesGetData, ThrowOnError>): RequestResult<ListStashesApiV1StashesGetResponses, ListStashesApiV1StashesGetErrors, ThrowOnError> => (options.client ?? client).get<ListStashesApiV1StashesGetResponses, ListStashesApiV1StashesGetErrors, ThrowOnError>({ url: '/api/v1/stashes/', ...options });

/**
 * Add Text Stash
 */
export const addTextStashApiV1StashesTextPost = <ThrowOnError extends boolean = false>(options: Options<AddTextStashApiV1StashesTextPostData, ThrowOnError>): RequestResult<AddTextStashApiV1StashesTextPostResponses, AddTextStashApiV1StashesTextPostErrors, ThrowOnError> => (options.client ?? client).post<AddTextStashApiV1StashesTextPostResponses, AddTextStashApiV1StashesTextPostErrors, ThrowOnError>({
    url: '/api/v1/stashes/text',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add Binary Stash
 */
export const addBinaryStashApiV1StashesFilePost = <ThrowOnError extends boolean = false>(options: Options<AddBinaryStashApiV1StashesFilePostData, ThrowOnError>): RequestResult<AddBinaryStashApiV1StashesFilePostResponses, AddBinaryStashApiV1StashesFilePostErrors, ThrowOnError> => (options.client ?? client).post<AddBinaryStashApiV1StashesFilePostResponses, AddBinaryStashApiV1StashesFilePostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/stashes/file',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get File Stash
 */
export const getFileStashApiV1StashesFileSlugGet = <ThrowOnError extends boolean = false>(options: Options<GetFileStashApiV1StashesFileSlugGetData, ThrowOnError>): RequestResult<GetFileStashApiV1StashesFileSlugGetResponses, GetFileStashApiV1StashesFileSlugGetErrors, ThrowOnError> => (options.client ?? client).get<GetFileStashApiV1StashesFileSlugGetResponses, GetFileStashApiV1StashesFileSlugGetErrors, ThrowOnError>({ url: '/api/v1/stashes/file/{slug}', ...options });

/**
 * Get Text Stash
 */
export const getTextStashApiV1StashesTextSlugGet = <ThrowOnError extends boolean = false>(options: Options<GetTextStashApiV1StashesTextSlugGetData, ThrowOnError>): RequestResult<GetTextStashApiV1StashesTextSlugGetResponses, GetTextStashApiV1StashesTextSlugGetErrors, ThrowOnError> => (options.client ?? client).get<GetTextStashApiV1StashesTextSlugGetResponses, GetTextStashApiV1StashesTextSlugGetErrors, ThrowOnError>({ url: '/api/v1/stashes/text/{slug}', ...options });

/**
 * Get Stash Metadata
 */
export const getStashMetadataApiV1StashesMetadataSlugGet = <ThrowOnError extends boolean = false>(options: Options<GetStashMetadataApiV1StashesMetadataSlugGetData, ThrowOnError>): RequestResult<GetStashMetadataApiV1StashesMetadataSlugGetResponses, GetStashMetadataApiV1StashesMetadataSlugGetErrors, ThrowOnError> => (options.client ?? client).get<GetStashMetadataApiV1StashesMetadataSlugGetResponses, GetStashMetadataApiV1StashesMetadataSlugGetErrors, ThrowOnError>({ url: '/api/v1/stashes/metadata/{slug}', ...options });

/**
 * Get Stash Views
 */
export const getStashViewsApiV1StashesViewsSlugGet = <ThrowOnError extends boolean = false>(options: Options<GetStashViewsApiV1StashesViewsSlugGetData, ThrowOnError>): RequestResult<GetStashViewsApiV1StashesViewsSlugGetResponses, GetStashViewsApiV1StashesViewsSlugGetErrors, ThrowOnError> => (options.client ?? client).get<GetStashViewsApiV1StashesViewsSlugGetResponses, GetStashViewsApiV1StashesViewsSlugGetErrors, ThrowOnError>({ url: '/api/v1/stashes/views/{slug}', ...options });

/**
 * Google Login
 */
export const googleLoginApiV1AuthGoogleGet = <ThrowOnError extends boolean = false>(options?: Options<GoogleLoginApiV1AuthGoogleGetData, ThrowOnError>): RequestResult<GoogleLoginApiV1AuthGoogleGetResponses, GoogleLoginApiV1AuthGoogleGetErrors, ThrowOnError> => (options?.client ?? client).get<GoogleLoginApiV1AuthGoogleGetResponses, GoogleLoginApiV1AuthGoogleGetErrors, ThrowOnError>({ url: '/api/v1/auth/google', ...options });

/**
 * Google Callback
 */
export const googleCallbackApiV1AuthGoogleCallbackGet = <ThrowOnError extends boolean = false>(options: Options<GoogleCallbackApiV1AuthGoogleCallbackGetData, ThrowOnError>): RequestResult<unknown, GoogleCallbackApiV1AuthGoogleCallbackGetErrors, ThrowOnError> => (options.client ?? client).get<unknown, GoogleCallbackApiV1AuthGoogleCallbackGetErrors, ThrowOnError>({ url: '/api/v1/auth/google/callback', ...options });

/**
 * Get Me
 */
export const getMeApiV1AuthGoogleMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMeApiV1AuthGoogleMeGetData, ThrowOnError>): RequestResult<GetMeApiV1AuthGoogleMeGetResponses, GetMeApiV1AuthGoogleMeGetErrors, ThrowOnError> => (options?.client ?? client).get<GetMeApiV1AuthGoogleMeGetResponses, GetMeApiV1AuthGoogleMeGetErrors, ThrowOnError>({ url: '/api/v1/auth/google/me', ...options });

/**
 * Get Config
 */
export const getConfigApiV1ConfigMaxUploadBytesGet = <ThrowOnError extends boolean = false>(options?: Options<GetConfigApiV1ConfigMaxUploadBytesGetData, ThrowOnError>): RequestResult<GetConfigApiV1ConfigMaxUploadBytesGetResponses, GetConfigApiV1ConfigMaxUploadBytesGetErrors, ThrowOnError> => (options?.client ?? client).get<GetConfigApiV1ConfigMaxUploadBytesGetResponses, GetConfigApiV1ConfigMaxUploadBytesGetErrors, ThrowOnError>({ url: '/api/v1/config/max-upload-bytes', ...options });
