// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_add_binary_stash_api_v1_stashes_file_post
 */
export type BodyAddBinaryStashApiV1StashesFilePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CreateStashRow
 */
export type CreateStashRow = {
    /**
     * Id
     */
    id_: number;
    /**
     * Is Binary
     */
    is_binary: boolean;
    /**
     * Slug
     */
    slug: string;
    /**
     * Added
     */
    added: string;
};

/**
 * GetStashBySlugRow
 */
export type GetStashBySlugRow = {
    /**
     * Id
     */
    id_: number;
    /**
     * Is Binary
     */
    is_binary: boolean;
    /**
     * Slug
     */
    slug: string;
    /**
     * Added
     */
    added: string;
    /**
     * Added By Ip
     */
    added_by_ip: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ListStashesRow
 */
export type ListStashesRow = {
    /**
     * Id
     */
    id_: number;
    /**
     * Is Binary
     */
    is_binary: boolean;
    /**
     * Slug
     */
    slug: string;
    /**
     * Added
     */
    added: string;
    /**
     * Added By Ip
     */
    added_by_ip: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id_: number;
    /**
     * Google Sub
     */
    google_sub: string;
    /**
     * Email
     */
    email: string;
    /**
     * Created
     */
    created: string;
    /**
     * Last Login
     */
    last_login: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListStashesApiV1StashesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page
         */
        page: number;
        /**
         * Take
         */
        take: number;
    };
    url: '/api/v1/stashes/';
};

export type ListStashesApiV1StashesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type ListStashesApiV1StashesGetError = ListStashesApiV1StashesGetErrors[keyof ListStashesApiV1StashesGetErrors];

export type ListStashesApiV1StashesGetResponses = {
    /**
     * Response List Stashes Api V1 Stashes  Get
     *
     * Successful Response
     */
    200: Array<ListStashesRow>;
};

export type ListStashesApiV1StashesGetResponse = ListStashesApiV1StashesGetResponses[keyof ListStashesApiV1StashesGetResponses];

export type AddTextStashApiV1StashesTextPostData = {
    /**
     * Content
     */
    body: string;
    path?: never;
    query?: never;
    url: '/api/v1/stashes/text';
};

export type AddTextStashApiV1StashesTextPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type AddTextStashApiV1StashesTextPostError = AddTextStashApiV1StashesTextPostErrors[keyof AddTextStashApiV1StashesTextPostErrors];

export type AddTextStashApiV1StashesTextPostResponses = {
    /**
     * Successful Response
     */
    201: CreateStashRow;
};

export type AddTextStashApiV1StashesTextPostResponse = AddTextStashApiV1StashesTextPostResponses[keyof AddTextStashApiV1StashesTextPostResponses];

export type AddBinaryStashApiV1StashesFilePostData = {
    body: BodyAddBinaryStashApiV1StashesFilePost;
    path?: never;
    query?: never;
    url: '/api/v1/stashes/file';
};

export type AddBinaryStashApiV1StashesFilePostErrors = {
    /**
     * Content Too Large
     */
    413: Message;
    /**
     * Unprocessable Content
     */
    422: Message;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type AddBinaryStashApiV1StashesFilePostError = AddBinaryStashApiV1StashesFilePostErrors[keyof AddBinaryStashApiV1StashesFilePostErrors];

export type AddBinaryStashApiV1StashesFilePostResponses = {
    /**
     * Successful Response
     */
    201: CreateStashRow;
};

export type AddBinaryStashApiV1StashesFilePostResponse = AddBinaryStashApiV1StashesFilePostResponses[keyof AddBinaryStashApiV1StashesFilePostResponses];

export type GetFileStashApiV1StashesFileSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/stashes/file/{slug}';
};

export type GetFileStashApiV1StashesFileSlugGetErrors = {
    /**
     * Bad Request
     */
    400: Message;
    /**
     * Not Found
     */
    404: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GetFileStashApiV1StashesFileSlugGetError = GetFileStashApiV1StashesFileSlugGetErrors[keyof GetFileStashApiV1StashesFileSlugGetErrors];

export type GetFileStashApiV1StashesFileSlugGetResponses = {
    /**
     * Successful Response
     */
    200: Blob | File;
};

export type GetFileStashApiV1StashesFileSlugGetResponse = GetFileStashApiV1StashesFileSlugGetResponses[keyof GetFileStashApiV1StashesFileSlugGetResponses];

export type GetTextStashApiV1StashesTextSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/stashes/text/{slug}';
};

export type GetTextStashApiV1StashesTextSlugGetErrors = {
    /**
     * Bad Request
     */
    400: Message;
    /**
     * Not Found
     */
    404: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GetTextStashApiV1StashesTextSlugGetError = GetTextStashApiV1StashesTextSlugGetErrors[keyof GetTextStashApiV1StashesTextSlugGetErrors];

export type GetTextStashApiV1StashesTextSlugGetResponses = {
    /**
     * Response Get Text Stash Api V1 Stashes Text  Slug  Get
     *
     * Successful Response
     */
    200: string;
};

export type GetTextStashApiV1StashesTextSlugGetResponse = GetTextStashApiV1StashesTextSlugGetResponses[keyof GetTextStashApiV1StashesTextSlugGetResponses];

export type GetStashMetadataApiV1StashesMetadataSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/stashes/metadata/{slug}';
};

export type GetStashMetadataApiV1StashesMetadataSlugGetErrors = {
    /**
     * Not Found
     */
    404: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GetStashMetadataApiV1StashesMetadataSlugGetError = GetStashMetadataApiV1StashesMetadataSlugGetErrors[keyof GetStashMetadataApiV1StashesMetadataSlugGetErrors];

export type GetStashMetadataApiV1StashesMetadataSlugGetResponses = {
    /**
     * Successful Response
     */
    200: GetStashBySlugRow;
};

export type GetStashMetadataApiV1StashesMetadataSlugGetResponse = GetStashMetadataApiV1StashesMetadataSlugGetResponses[keyof GetStashMetadataApiV1StashesMetadataSlugGetResponses];

export type GetStashViewsApiV1StashesViewsSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query: {
        /**
         * Unique
         */
        unique: boolean;
    };
    url: '/api/v1/stashes/views/{slug}';
};

export type GetStashViewsApiV1StashesViewsSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GetStashViewsApiV1StashesViewsSlugGetError = GetStashViewsApiV1StashesViewsSlugGetErrors[keyof GetStashViewsApiV1StashesViewsSlugGetErrors];

export type GetStashViewsApiV1StashesViewsSlugGetResponses = {
    /**
     * Response Get Stash Views Api V1 Stashes Views  Slug  Get
     *
     * Successful Response
     */
    200: number;
};

export type GetStashViewsApiV1StashesViewsSlugGetResponse = GetStashViewsApiV1StashesViewsSlugGetResponses[keyof GetStashViewsApiV1StashesViewsSlugGetResponses];

export type GoogleLoginApiV1AuthGoogleGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/google';
};

export type GoogleLoginApiV1AuthGoogleGetErrors = {
    /**
     * Unauthorized
     */
    401: Message;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GoogleLoginApiV1AuthGoogleGetError = GoogleLoginApiV1AuthGoogleGetErrors[keyof GoogleLoginApiV1AuthGoogleGetErrors];

export type GoogleCallbackApiV1AuthGoogleCallbackGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
    };
    url: '/api/v1/auth/google/callback';
};

export type GoogleCallbackApiV1AuthGoogleCallbackGetErrors = {
    /**
     * Bad Request
     */
    400: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GoogleCallbackApiV1AuthGoogleCallbackGetError = GoogleCallbackApiV1AuthGoogleCallbackGetErrors[keyof GoogleCallbackApiV1AuthGoogleCallbackGetErrors];

export type GetMeApiV1AuthGoogleMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/google/me';
};

export type GetMeApiV1AuthGoogleMeGetErrors = {
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GetMeApiV1AuthGoogleMeGetError = GetMeApiV1AuthGoogleMeGetErrors[keyof GetMeApiV1AuthGoogleMeGetErrors];

export type GetMeApiV1AuthGoogleMeGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetMeApiV1AuthGoogleMeGetResponse = GetMeApiV1AuthGoogleMeGetResponses[keyof GetMeApiV1AuthGoogleMeGetResponses];

export type GetConfigApiV1ConfigMaxUploadBytesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/max-upload-bytes';
};

export type GetConfigApiV1ConfigMaxUploadBytesGetErrors = {
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GetConfigApiV1ConfigMaxUploadBytesGetError = GetConfigApiV1ConfigMaxUploadBytesGetErrors[keyof GetConfigApiV1ConfigMaxUploadBytesGetErrors];

export type GetConfigApiV1ConfigMaxUploadBytesGetResponses = {
    /**
     * Response Get Config Api V1 Config Max Upload Bytes Get
     *
     * Successful Response
     */
    200: number;
};

export type GetConfigApiV1ConfigMaxUploadBytesGetResponse = GetConfigApiV1ConfigMaxUploadBytesGetResponses[keyof GetConfigApiV1ConfigMaxUploadBytesGetResponses];
