// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_add_binary_stash_api_v1_stashes_file_post
 */
export type BodyAddBinaryStashApiV1StashesFilePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * GetStashBySlugRow
 */
export type GetStashBySlugRow = {
    /**
     * Id
     */
    id_: number;
    /**
     * Is Binary
     */
    is_binary: boolean;
    /**
     * Added
     */
    added: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * Stash
 */
export type Stash = {
    /**
     * Id
     */
    id_: number;
    /**
     * Is Binary
     */
    is_binary: boolean;
    /**
     * Slug
     */
    slug: string;
    /**
     * Added
     */
    added: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListStashesApiV1StashesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/stashes/';
};

export type ListStashesApiV1StashesGetErrors = {
    /**
     * Internal Server Error
     */
    500: Message;
};

export type ListStashesApiV1StashesGetError = ListStashesApiV1StashesGetErrors[keyof ListStashesApiV1StashesGetErrors];

export type ListStashesApiV1StashesGetResponses = {
    /**
     * Response List Stashes Api V1 Stashes  Get
     *
     * Successful Response
     */
    200: Array<Stash>;
};

export type ListStashesApiV1StashesGetResponse = ListStashesApiV1StashesGetResponses[keyof ListStashesApiV1StashesGetResponses];

export type AddTextStashApiV1StashesTextPostData = {
    /**
     * Content
     */
    body: string;
    path?: never;
    query?: never;
    url: '/api/v1/stashes/text';
};

export type AddTextStashApiV1StashesTextPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type AddTextStashApiV1StashesTextPostError = AddTextStashApiV1StashesTextPostErrors[keyof AddTextStashApiV1StashesTextPostErrors];

export type AddTextStashApiV1StashesTextPostResponses = {
    /**
     * Successful Response
     */
    201: Stash;
};

export type AddTextStashApiV1StashesTextPostResponse = AddTextStashApiV1StashesTextPostResponses[keyof AddTextStashApiV1StashesTextPostResponses];

export type AddBinaryStashApiV1StashesFilePostData = {
    body: BodyAddBinaryStashApiV1StashesFilePost;
    path?: never;
    query?: never;
    url: '/api/v1/stashes/file';
};

export type AddBinaryStashApiV1StashesFilePostErrors = {
    /**
     * Unprocessable Content
     */
    422: Message;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type AddBinaryStashApiV1StashesFilePostError = AddBinaryStashApiV1StashesFilePostErrors[keyof AddBinaryStashApiV1StashesFilePostErrors];

export type AddBinaryStashApiV1StashesFilePostResponses = {
    /**
     * Successful Response
     */
    201: Stash;
};

export type AddBinaryStashApiV1StashesFilePostResponse = AddBinaryStashApiV1StashesFilePostResponses[keyof AddBinaryStashApiV1StashesFilePostResponses];

export type GetFileStashApiV1StashesFileSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/stashes/file/{slug}';
};

export type GetFileStashApiV1StashesFileSlugGetErrors = {
    /**
     * Not Found
     */
    404: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GetFileStashApiV1StashesFileSlugGetError = GetFileStashApiV1StashesFileSlugGetErrors[keyof GetFileStashApiV1StashesFileSlugGetErrors];

export type GetFileStashApiV1StashesFileSlugGetResponses = {
    /**
     * Binary file
     */
    200: Blob | File;
};

export type GetFileStashApiV1StashesFileSlugGetResponse = GetFileStashApiV1StashesFileSlugGetResponses[keyof GetFileStashApiV1StashesFileSlugGetResponses];

export type GetTextStashApiV1StashesTextSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/stashes/text/{slug}';
};

export type GetTextStashApiV1StashesTextSlugGetErrors = {
    /**
     * Not Found
     */
    404: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GetTextStashApiV1StashesTextSlugGetError = GetTextStashApiV1StashesTextSlugGetErrors[keyof GetTextStashApiV1StashesTextSlugGetErrors];

export type GetTextStashApiV1StashesTextSlugGetResponses = {
    /**
     * Response Get Text Stash Api V1 Stashes Text  Slug  Get
     *
     * Successful Response
     */
    200: string;
};

export type GetTextStashApiV1StashesTextSlugGetResponse = GetTextStashApiV1StashesTextSlugGetResponses[keyof GetTextStashApiV1StashesTextSlugGetResponses];

export type GetStashMetadataApiV1StashesMetadataSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/stashes/metadata/{slug}';
};

export type GetStashMetadataApiV1StashesMetadataSlugGetErrors = {
    /**
     * Not Found
     */
    404: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type GetStashMetadataApiV1StashesMetadataSlugGetError = GetStashMetadataApiV1StashesMetadataSlugGetErrors[keyof GetStashMetadataApiV1StashesMetadataSlugGetErrors];

export type GetStashMetadataApiV1StashesMetadataSlugGetResponses = {
    /**
     * Successful Response
     */
    200: GetStashBySlugRow;
};

export type GetStashMetadataApiV1StashesMetadataSlugGetResponse = GetStashMetadataApiV1StashesMetadataSlugGetResponses[keyof GetStashMetadataApiV1StashesMetadataSlugGetResponses];
