// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Stash
 */
export type Stash = {
    /**
     * Id
     */
    id_: number;
    /**
     * Is Binary
     */
    is_binary: boolean;
    /**
     * Slug
     */
    slug: string;
    /**
     * Added
     */
    added: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type AddTextStashApiV1StashesTextPostData = {
    /**
     * Content
     */
    body: string;
    path?: never;
    query?: never;
    url: '/api/v1/stashes/text';
};

export type AddTextStashApiV1StashesTextPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddTextStashApiV1StashesTextPostError = AddTextStashApiV1StashesTextPostErrors[keyof AddTextStashApiV1StashesTextPostErrors];

export type AddTextStashApiV1StashesTextPostResponses = {
    /**
     * Successful Response
     */
    201: Stash;
};

export type AddTextStashApiV1StashesTextPostResponse = AddTextStashApiV1StashesTextPostResponses[keyof AddTextStashApiV1StashesTextPostResponses];

export type ListStashesApiV1StashesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/stashes/';
};

export type ListStashesApiV1StashesGetResponses = {
    /**
     * Response List Stashes Api V1 Stashes  Get
     *
     * Successful Response
     */
    200: Array<Stash>;
};

export type ListStashesApiV1StashesGetResponse = ListStashesApiV1StashesGetResponses[keyof ListStashesApiV1StashesGetResponses];

export type AddBinaryStashApiV1StashesFilePostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Filepath
         */
        filepath: string;
    };
    url: '/api/v1/stashes/file';
};

export type AddBinaryStashApiV1StashesFilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddBinaryStashApiV1StashesFilePostError = AddBinaryStashApiV1StashesFilePostErrors[keyof AddBinaryStashApiV1StashesFilePostErrors];

export type AddBinaryStashApiV1StashesFilePostResponses = {
    /**
     * Successful Response
     */
    201: Stash;
};

export type AddBinaryStashApiV1StashesFilePostResponse = AddBinaryStashApiV1StashesFilePostResponses[keyof AddBinaryStashApiV1StashesFilePostResponses];

export type GetStashApiV1StashesSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/stashes/{slug}';
};

export type GetStashApiV1StashesSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStashApiV1StashesSlugGetError = GetStashApiV1StashesSlugGetErrors[keyof GetStashApiV1StashesSlugGetErrors];

export type GetStashApiV1StashesSlugGetResponses = {
    /**
     * Response Get Stash Api V1 Stashes  Slug  Get
     *
     * Successful Response
     */
    200: string;
};

export type GetStashApiV1StashesSlugGetResponse = GetStashApiV1StashesSlugGetResponses[keyof GetStashApiV1StashesSlugGetResponses];
