# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: query.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "CreateStashRow",
    "GetActiveStashLockoutRow",
    "GetOAuthStateRow",
    "GetStashBySlugRow",
    "GetStashRevocationRow",
    "GetStashRow",
    "ListStashesRow",
    "QueryResults",
    "check_slug_exists",
    "create_o_auth_state",
    "create_session",
    "create_stash",
    "create_stash_binary_path",
    "create_stash_expiry",
    "create_stash_lockout",
    "create_stash_one_time_view",
    "create_stash_password_attempt",
    "create_stash_password_hash",
    "create_stash_revocation",
    "create_stash_text_content",
    "create_stash_view",
    "delete_o_auth_state",
    "get_active_stash_lockout",
    "get_o_auth_state",
    "get_stash",
    "get_stash_binary_path",
    "get_stash_by_slug",
    "get_stash_expiry",
    "get_stash_one_time_view",
    "get_stash_password_hash",
    "get_stash_revocation",
    "get_stash_text_content",
    "get_stash_unique_views",
    "get_stash_unique_views_by_slug",
    "get_stash_views",
    "get_stash_views_by_slug",
    "list_stashes",
    "upsert_user",
)

import datetime
import typing

import pydantic

if typing.TYPE_CHECKING:
    import collections.abc

    import psycopg
    import psycopg.rows

    type QueryResultsArgsType = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = psycopg.AsyncConnection[psycopg.rows.TupleRow]

from . import models


class GetOAuthStateRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    state: str
    code_verifier: str
    expires: datetime.datetime
    ip_address: str


class GetStashRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    is_binary: bool
    slug: str
    added: datetime.datetime
    added_by_ip: str


class GetStashBySlugRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    is_binary: bool
    slug: str
    added: datetime.datetime
    added_by_ip: str


class ListStashesRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    is_binary: bool
    slug: str
    added: datetime.datetime
    added_by_ip: str


class CreateStashRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    is_binary: bool
    slug: str
    added: datetime.datetime


class GetActiveStashLockoutRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    added: datetime.datetime
    expires: datetime.datetime


class GetStashRevocationRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    revoked_at: datetime.datetime
    revoked_by_ip: str


CREATE_O_AUTH_STATE: typing.Final[typing.LiteralString] = """-- name: CreateOAuthState :exec
INSERT INTO oauth_states (
    state,
    code_verifier,
    expires,
    ip_address
)
VALUES (%(p1)s, %(p2)s, %(p3)s, %(p4)s)
"""

GET_O_AUTH_STATE: typing.Final[typing.LiteralString] = """-- name: GetOAuthState :one
SELECT
    state,
    code_verifier,
    expires,
    ip_address
FROM oauth_states
WHERE state = %(p1)s
"""

DELETE_O_AUTH_STATE: typing.Final[typing.LiteralString] = """-- name: DeleteOAuthState :one
DELETE FROM oauth_states
WHERE state = %(p1)s
RETURNING state, code_verifier, created, expires, ip_address
"""

UPSERT_USER: typing.Final[typing.LiteralString] = """-- name: UpsertUser :one
INSERT INTO users (
    google_sub,
    email
)
VALUES (%(p1)s, %(p2)s)
ON CONFLICT (google_sub)
DO UPDATE SET
    email = EXCLUDED.email,
    last_login = CURRENT_TIMESTAMP
RETURNING id, google_sub, email, created, last_login
"""

CREATE_SESSION: typing.Final[typing.LiteralString] = """-- name: CreateSession :exec
INSERT INTO sessions (
    user_id,
    token_hash,
    expires
)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

GET_STASH: typing.Final[typing.LiteralString] = """-- name: GetStash :one
SELECT
    id,
    is_binary,
    slug,
    added,
    added_by_ip
FROM stashes
WHERE id = %(p1)s
"""

GET_STASH_BY_SLUG: typing.Final[typing.LiteralString] = """-- name: GetStashBySlug :one
SELECT
    id,
    is_binary,
    slug,
    added,
    added_by_ip
FROM stashes
WHERE slug = %(p1)s
"""

LIST_STASHES: typing.Final[typing.LiteralString] = """-- name: ListStashes :many
SELECT
    id,
    is_binary,
    slug,
    added,
    added_by_ip
FROM stashes
ORDER BY added DESC, id DESC
LIMIT %(p1)s OFFSET %(p2)s
"""

GET_STASH_TEXT_CONTENT: typing.Final[typing.LiteralString] = """-- name: GetStashTextContent :one
SELECT content
FROM stashes_text_content
WHERE stash_id = %(p1)s
"""

GET_STASH_BINARY_PATH: typing.Final[typing.LiteralString] = """-- name: GetStashBinaryPath :one
SELECT file_path
FROM stashes_binary_paths
WHERE stash_id = %(p1)s
"""

CREATE_STASH: typing.Final[typing.LiteralString] = """-- name: CreateStash :one
INSERT INTO stashes (
    is_binary,
    slug,
    added_by_ip
)
VALUES (%(p1)s, %(p2)s, %(p3)s)
RETURNING
    id,
    is_binary,
    slug,
    added
"""

CREATE_STASH_TEXT_CONTENT: typing.Final[typing.LiteralString] = """-- name: CreateStashTextContent :exec
INSERT INTO stashes_text_content (
    stash_id,
    content
)
VALUES (%(p1)s, %(p2)s)
"""

CREATE_STASH_BINARY_PATH: typing.Final[typing.LiteralString] = """-- name: CreateStashBinaryPath :exec
INSERT INTO stashes_binary_paths (
    stash_id,
    file_path
)
VALUES (%(p1)s, %(p2)s)
"""

CHECK_SLUG_EXISTS: typing.Final[typing.LiteralString] = """-- name: CheckSlugExists :one
SELECT EXISTS (
    SELECT 1
    FROM stashes
    WHERE slug = %(p1)s
)
"""

CREATE_STASH_VIEW: typing.Final[typing.LiteralString] = """-- name: CreateStashView :exec
INSERT INTO stash_views (
    stash_id,
    ip_address
)
VALUES (%(p1)s, %(p2)s)
"""

CREATE_STASH_PASSWORD_ATTEMPT: typing.Final[typing.LiteralString] = """-- name: CreateStashPasswordAttempt :exec
INSERT INTO stash_password_attempts (
    stash_id,
    ip_address,
    successful
)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

CREATE_STASH_LOCKOUT: typing.Final[typing.LiteralString] = """-- name: CreateStashLockout :exec
INSERT INTO stash_lockouts (
    stash_id,
    ip_address,
    expires
)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

GET_ACTIVE_STASH_LOCKOUT: typing.Final[typing.LiteralString] = """-- name: GetActiveStashLockout :one
SELECT
    id,
    added,
    expires
FROM stash_lockouts
WHERE stash_id = %(p1)s
  AND ip_address = %(p2)s
  AND expires > CURRENT_TIMESTAMP
ORDER BY expires DESC
LIMIT 1
"""

GET_STASH_VIEWS: typing.Final[typing.LiteralString] = """-- name: GetStashViews :one
SELECT COUNT(*)
FROM stash_views
WHERE stash_id = %(p1)s
"""

GET_STASH_UNIQUE_VIEWS: typing.Final[typing.LiteralString] = """-- name: GetStashUniqueViews :one
SELECT COUNT(DISTINCT ip_address)
FROM stash_views
WHERE stash_id = %(p1)s
"""

GET_STASH_VIEWS_BY_SLUG: typing.Final[typing.LiteralString] = """-- name: GetStashViewsBySlug :one
SELECT COUNT(*)
FROM stash_views
JOIN stashes
    ON stashes.id = stash_views.stash_id
WHERE stashes.slug = %(p1)s
"""

GET_STASH_UNIQUE_VIEWS_BY_SLUG: typing.Final[typing.LiteralString] = """-- name: GetStashUniqueViewsBySlug :one
SELECT COUNT(DISTINCT stash_views.ip_address)
FROM stash_views
JOIN stashes
    ON stashes.id = stash_views.stash_id
WHERE stashes.slug = %(p1)s
"""

GET_STASH_EXPIRY: typing.Final[typing.LiteralString] = """-- name: GetStashExpiry :one
SELECT expires_at
FROM stashes_expiries
WHERE stash_id = %(p1)s
"""

CREATE_STASH_EXPIRY: typing.Final[typing.LiteralString] = """-- name: CreateStashExpiry :exec
INSERT INTO stashes_expiries (
    stash_id,
    expires_at
)
VALUES (%(p1)s, %(p2)s)
"""

GET_STASH_ONE_TIME_VIEW: typing.Final[typing.LiteralString] = """-- name: GetStashOneTimeView :one
SELECT stash_id
FROM stashes_one_time_views
WHERE stash_id = %(p1)s
"""

CREATE_STASH_ONE_TIME_VIEW: typing.Final[typing.LiteralString] = """-- name: CreateStashOneTimeView :exec
INSERT INTO stashes_one_time_views (
    stash_id
)
VALUES (%(p1)s)
"""

GET_STASH_PASSWORD_HASH: typing.Final[typing.LiteralString] = """-- name: GetStashPasswordHash :one
SELECT password_hash
FROM stashes_password_hashes
WHERE stash_id = %(p1)s
"""

CREATE_STASH_PASSWORD_HASH: typing.Final[typing.LiteralString] = """-- name: CreateStashPasswordHash :exec
INSERT INTO stashes_password_hashes (
    stash_id,
    password_hash
)
VALUES (%(p1)s, %(p2)s)
"""

GET_STASH_REVOCATION: typing.Final[typing.LiteralString] = """-- name: GetStashRevocation :one
SELECT
    revoked_at,
    revoked_by_ip
FROM stashes_revocations
WHERE stash_id = %(p1)s
"""

CREATE_STASH_REVOCATION: typing.Final[typing.LiteralString] = """-- name: CreateStashRevocation :exec
INSERT INTO stashes_revocations (
    stash_id,
    revoked_at,
    revoked_by_ip
)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""


class QueryResults[T]:
    __slots__ = ("_conn", "_cursor", "_decode_hook", "_iterator", "_params", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: typing.LiteralString,
        decode_hook: collections.abc.Callable[[psycopg.rows.TupleRow], T],
        params: dict[str, QueryResultsArgsType] | None = None,
    ) -> None:
        self._conn = conn
        self._sql: typing.LiteralString = sql
        self._decode_hook = decode_hook
        self._params = params
        self._cursor: psycopg.AsyncCursor[psycopg.rows.TupleRow] | None = None
        self._iterator: collections.abc.AsyncIterator[psycopg.rows.TupleRow] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await (await self._conn.execute(self._sql, self._params)).fetchall()
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = await self._conn.execute(self._sql, self._params)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def create_o_auth_state(conn: ConnectionLike, *, state: str, code_verifier: str, expires: datetime.datetime, ip_address: str) -> None:
    await conn.execute(CREATE_O_AUTH_STATE, {"p1": state, "p2": code_verifier, "p3": expires, "p4": ip_address})


async def get_o_auth_state(conn: ConnectionLike, *, state: str) -> GetOAuthStateRow | None:
    row = await (await conn.execute(GET_O_AUTH_STATE, {"p1": state})).fetchone()
    if row is None:
        return None
    return GetOAuthStateRow(state=row[0], code_verifier=row[1], expires=row[2], ip_address=str(row[3]))


async def delete_o_auth_state(conn: ConnectionLike, *, state: str) -> models.OauthState | None:
    row = await (await conn.execute(DELETE_O_AUTH_STATE, {"p1": state})).fetchone()
    if row is None:
        return None
    return models.OauthState(state=row[0], code_verifier=row[1], created=row[2], expires=row[3], ip_address=str(row[4]))


async def upsert_user(conn: ConnectionLike, *, google_sub: str, email: str) -> models.User | None:
    row = await (await conn.execute(UPSERT_USER, {"p1": google_sub, "p2": email})).fetchone()
    if row is None:
        return None
    return models.User(id_=row[0], google_sub=row[1], email=row[2], created=row[3], last_login=row[4])


async def create_session(conn: ConnectionLike, *, user_id: int, token_hash: str, expires: datetime.datetime) -> None:
    await conn.execute(CREATE_SESSION, {"p1": user_id, "p2": token_hash, "p3": expires})


async def get_stash(conn: ConnectionLike, *, id_: int) -> GetStashRow | None:
    row = await (await conn.execute(GET_STASH, {"p1": id_})).fetchone()
    if row is None:
        return None
    return GetStashRow(id_=row[0], is_binary=row[1], slug=row[2], added=row[3], added_by_ip=str(row[4]))


async def get_stash_by_slug(conn: ConnectionLike, *, slug: str) -> GetStashBySlugRow | None:
    row = await (await conn.execute(GET_STASH_BY_SLUG, {"p1": slug})).fetchone()
    if row is None:
        return None
    return GetStashBySlugRow(id_=row[0], is_binary=row[1], slug=row[2], added=row[3], added_by_ip=str(row[4]))


def list_stashes(conn: ConnectionLike, *, limit: int, offset: int) -> QueryResults[ListStashesRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListStashesRow:
        return ListStashesRow(id_=row[0], is_binary=row[1], slug=row[2], added=row[3], added_by_ip=str(row[4]))

    return QueryResults(conn, LIST_STASHES, _decode_hook, {"p1": limit, "p2": offset})


async def get_stash_text_content(conn: ConnectionLike, *, stash_id: int) -> str | None:
    row = await (await conn.execute(GET_STASH_TEXT_CONTENT, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_stash_binary_path(conn: ConnectionLike, *, stash_id: int) -> str | None:
    row = await (await conn.execute(GET_STASH_BINARY_PATH, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_stash(conn: ConnectionLike, *, is_binary: bool, slug: str, added_by_ip: str) -> CreateStashRow | None:
    row = await (await conn.execute(CREATE_STASH, {"p1": is_binary, "p2": slug, "p3": added_by_ip})).fetchone()
    if row is None:
        return None
    return CreateStashRow(id_=row[0], is_binary=row[1], slug=row[2], added=row[3])


async def create_stash_text_content(conn: ConnectionLike, *, stash_id: int, content: str) -> None:
    await conn.execute(CREATE_STASH_TEXT_CONTENT, {"p1": stash_id, "p2": content})


async def create_stash_binary_path(conn: ConnectionLike, *, stash_id: int, file_path: str) -> None:
    await conn.execute(CREATE_STASH_BINARY_PATH, {"p1": stash_id, "p2": file_path})


async def check_slug_exists(conn: ConnectionLike, *, slug: str) -> bool | None:
    row = await (await conn.execute(CHECK_SLUG_EXISTS, {"p1": slug})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_stash_view(conn: ConnectionLike, *, stash_id: int, ip_address: str) -> None:
    await conn.execute(CREATE_STASH_VIEW, {"p1": stash_id, "p2": ip_address})


async def create_stash_password_attempt(conn: ConnectionLike, *, stash_id: int, ip_address: str, successful: bool) -> None:
    await conn.execute(CREATE_STASH_PASSWORD_ATTEMPT, {"p1": stash_id, "p2": ip_address, "p3": successful})


async def create_stash_lockout(conn: ConnectionLike, *, stash_id: int, ip_address: str, expires: datetime.datetime) -> None:
    await conn.execute(CREATE_STASH_LOCKOUT, {"p1": stash_id, "p2": ip_address, "p3": expires})


async def get_active_stash_lockout(conn: ConnectionLike, *, stash_id: int, ip_address: str) -> GetActiveStashLockoutRow | None:
    row = await (await conn.execute(GET_ACTIVE_STASH_LOCKOUT, {"p1": stash_id, "p2": ip_address})).fetchone()
    if row is None:
        return None
    return GetActiveStashLockoutRow(id_=row[0], added=row[1], expires=row[2])


async def get_stash_views(conn: ConnectionLike, *, stash_id: int) -> int | None:
    row = await (await conn.execute(GET_STASH_VIEWS, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_stash_unique_views(conn: ConnectionLike, *, stash_id: int) -> int | None:
    row = await (await conn.execute(GET_STASH_UNIQUE_VIEWS, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_stash_views_by_slug(conn: ConnectionLike, *, slug: str) -> int | None:
    row = await (await conn.execute(GET_STASH_VIEWS_BY_SLUG, {"p1": slug})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_stash_unique_views_by_slug(conn: ConnectionLike, *, slug: str) -> int | None:
    row = await (await conn.execute(GET_STASH_UNIQUE_VIEWS_BY_SLUG, {"p1": slug})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_stash_expiry(conn: ConnectionLike, *, stash_id: int) -> datetime.datetime | None:
    row = await (await conn.execute(GET_STASH_EXPIRY, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_stash_expiry(conn: ConnectionLike, *, stash_id: int, expires_at: datetime.datetime) -> None:
    await conn.execute(CREATE_STASH_EXPIRY, {"p1": stash_id, "p2": expires_at})


async def get_stash_one_time_view(conn: ConnectionLike, *, stash_id: int) -> int | None:
    row = await (await conn.execute(GET_STASH_ONE_TIME_VIEW, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_stash_one_time_view(conn: ConnectionLike, *, stash_id: int) -> None:
    await conn.execute(CREATE_STASH_ONE_TIME_VIEW, {"p1": stash_id})


async def get_stash_password_hash(conn: ConnectionLike, *, stash_id: int) -> str | None:
    row = await (await conn.execute(GET_STASH_PASSWORD_HASH, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_stash_password_hash(conn: ConnectionLike, *, stash_id: int, password_hash: str) -> None:
    await conn.execute(CREATE_STASH_PASSWORD_HASH, {"p1": stash_id, "p2": password_hash})


async def get_stash_revocation(conn: ConnectionLike, *, stash_id: int) -> GetStashRevocationRow | None:
    row = await (await conn.execute(GET_STASH_REVOCATION, {"p1": stash_id})).fetchone()
    if row is None:
        return None
    return GetStashRevocationRow(revoked_at=row[0], revoked_by_ip=str(row[1]))


async def create_stash_revocation(conn: ConnectionLike, *, stash_id: int, revoked_at: datetime.datetime, revoked_by_ip: str) -> None:
    await conn.execute(CREATE_STASH_REVOCATION, {"p1": stash_id, "p2": revoked_at, "p3": revoked_by_ip})
