[project]
name = "api"
version = "0.1.0"
description = "The backend for Stash It"
readme = "README.md"
authors = [
    { name = "tristanbatchler", email = "info@tbat.me" }
]
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "argon2-cffi>=25.1.0",
    "authlib>=1.7.2",
    "fastapi[standard]>=0.141.1",
    "google-auth-oauthlib>=1.4.1",
    "inflect>=7.5.0",
    "lemminflect>=0.2.3",
    "psycopg-pool>=3.3.1",
    "psycopg[binary]>=3.2",
    "python-dotenv>=1.2.3",
    "ruff>=0.16.4",
    "uvicorn>=0.52.4",
]

[project.scripts]
api = "api:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "ruff>=0.16.4",
]

[tool.ruff]
exclude = [
    "src/api/db/query.py",
    "src/api/db/models.py",
    "src/api/db/__init__.py",
]

[tool.fastapi]
entrypoint = "api.main:app"
