nouns = [
    "cartman",
    "john",
    "pigeon",
    "dog",
    "corn",
    "boy",
    "homer",
    "marge",
    "bart",
    "toilet",
    "hacker",
    "fireman",
    "angel",
    "josh",
    "ratboy",
    "uncle",
    "nephew",
    "ferris",
    "goldie",
    "jeff",
    "bob",
]

verbs = [
    "kick",
    "eat",
    "hack",
    "assault",
    "hold",
    "marry",
    "kill",
    "bake",
    "bomb",
    "love",
    "catch",
    "hex",
    "vex",
    "wield",
    "scam",
    "stalk",
    "slap",
    "whack",
    "summon",
    "bite",
    "need",
    "want",
    "buy",
    "sell",
    "sniff",
    "lick",
    "hunt",
    "shoot",
    "mug",
    "smash",
    "haunt",
    "blame",
    "charm",
    "ban",
    "hug",
    "break",
    "have",
]

adjectives = [
    "smooth",
    "cooked",
    "bent",
    "pale",
    "upset",
    "smart",
    "dumb",
    "stupid",
    "amazed",
    "honest",
    "drunk",
    "toxic",
    "feral",
    "shady",
    "greasy",
    "mean",
    "sad",
    "scary",
    "goofy",
    "angry",
    "cute",
    "fast",
    "mad",
    "sick",
]

adverbs = [
    "soon",
    "now",
    "fast",
    "well",
    "hard",
    "late",
    "deep",
]