nouns = [
    "cartman",
    "john",
    "table",
    "beans",
    "fire",
    "japan",
    "door",
    "pigeon",
    "dog",
    "corn",
    "boy",
    "homer",
    "marge",
    "bart",
    "711",
    "stew",
    "toilet",
    "hacker",
    "fireman",
    "moon",
    "angel",
    "josh",
    "rat",
    "uncle",
    "nephew",
    "brainrot",
]

verbs = [
    "kick",
    "smooch",
    "sprint",
    "sing",
    "jump",
    "eat",
    "faint",
    "lie",
    "smile",
    "frown",
    "hack",
    "dismember",
    "assault",
    "flirt",
    "dance",
    "fly",
    "work",
    "hold",
    "marry",
    "kill",
    "mog",
]

adjectives = [
    "smooth",
    "cooked",
    "chopped",
    "battered",
    "straight",
    "bent",
    "smashed",
    "pale",
    "tanned",
    "violent",
    "upset",
    "pleased",
    "smart",
    "dumb",
    "stupid",
    "braindead",
    "amazed",
    "honest",
    "annoying",
]

adverbs = [
    "quickly",
    "softly",
    "quietly",
    "loudly",
    "sadly",
    "happily",
    "willingly",
    "woefully",
]